### ISSUE TITLE
Buttons show up but not working

### ISSUE THREAD

**Issue by shahriar49** [theendlessriver13/ee-task-start#3]
Hi,
I added the .js file to my TramperMonkey Userscripts and enabled it and see the three additional Green/Yellow/Red buttons on my GEE screen, but nothing happens when I click on them.
I appreciate if you help me with this issue.

**Comment by jkittner** [comment]
Hi, this only works if there are tasks on the list like this, but I guess that's the case for you? 
![grafik](https://user-images.githubusercontent.com/54631600/124524716-66230400-ddfc-11eb-811d-4b638d5259ad.png)
It currently also only works for images, not for features or tables. I need to add more CSS classes e.g. for features this one: `class="task local type-EXPORT_FEATURES awaiting-user-config"` as a separate button or add another loop to the existing function. I did not manage to do this yet.

Maybe you are trying to export features, not images?

To debug this you can add a `console.log(tasks);` between those two lines to see if it actually finds the tasks. 
https://github.com/theendlessriver13/ee-task-start/blob/01627d872bc8322660ef29dfee7030ef061e8b58/ee_task_start.js#L18-L19
Also maybe check your console for potential errors related to this user script?
You can also check the CSS classes when you right click on the run button and then select "inspect element" maybe they are different for you and so the selection fails? It should look like this. If not, we need to see how we can fix this.
```html
<div class="task local type-EXPORT_IMAGE awaiting-user-config"><div class="content">all_bands</div><span class="info">?</span><span class="run-button" style="">Run</span><span class="indicator"></span><span class="runningtime"></span></div>
```

I have so far only used this in chrome, because the login to earthengine is broken in firefox for me so I am stuck with this.

I hope this helps you getting started to find out where the issue is. I am happy to help and if there's anything that can be fixed from my side I will try to do this, let me know what you can find out.

**Comment by shahriar49** [comment]
Hi,
Thank you very much for your kind attention and quick reply. Yes I am exporting some feature classes and I really need such a function. Is it difficult to add support for feature classes or is the same as images? I am also using the Chrome.

P.S. I just changed EXPORT_IMAGE to EXPORT_FEATURES in the .js code and the buttons now react to clicking! Thank you very much. But I get an error from GEE in the export to asset window saying that:
**The asset ID is invalid.
Asset "projects/earthengine-public/assets/:listAssets" not found.**
However, when I click "Run" it starts to run without problem.

**Comment by jkittner** [comment]
can you check if the changes on this branch resolve the issue for you? https://github.com/theendlessriver13/ee-task-start/tree/allow-feature-export
I tested it for me and now it also gets features. I hope this more generic selection does not cause any other trouble.

**Comment by shahriar49** [comment]
Many thanks. Yes the buttons are working but it still shows me the error in the export to asset window:
**The asset ID is invalid.
Asset "projects/earthengine-public/assets/:listAssets" not found.**

When I click "Run" it starts to run without problem, but if I wanted to hit run for every export, I would do it from the start without using any Userscript. Can you help me to figure out what is the reason for this error?

**Comment by jkittner** [comment]
Ok, this was a bit harder:
- you get this error, because the script clicks the button before google has filled the asset field (the request is sent with asset_id = "")  (it does some checks there if it exists or something like this)
- because of that we need to wait with clicking the button until the field is populated, this is a bit tricky to do and since I am no javascript expert at all I am not sure if this is the correct way to go or what other issues can come up with this solution
- I pushed a first draft to the other branch, what it basically does is, instead of just getting the buttons, it gets the whole popup and checks if the asset box radio button is checked or not. If it is, it waits for the field to be filled with text (the asset_id) waiting 100 ms between checks (I maybe need to twek this) and then when the promise is resolved it clicks the button. If the radio button is not checked it just clicks in instantly.
- so this will be slower, maybe I can reduce the 100 ms wait a bit to make it faster

I hope this helps you a bit more. I will come back to this and merge it or improve it when needed in the next days.

**Comment by shahriar49** [comment]
Thank you very much for your kind attention :) I replaced the code but had to play with the delay value and increase it to work some times. I will inform you if I face any other thing.

**Comment by jkittner** [comment]
Good to hear. 👍 
I will think about the best value as well.
As far as I understand this, it should wait until the promise can be resolved, waiting the set value between checks. So a longer value should only make it overall slower, theoretically any value should work, but choosing it too low might slow down the browser since the checks are executed so often. Again, unfortunately I am no expert here so any advice is welcome and let me know what works best for you and what additional issues you ran into.

**Comment by shahriar49** [comment]
Just to add: The problem happens for the first tasks in the task list and the ones in the top will run with less error. When I increase the delay it becomes better and less items suffer from the error, but it completely depends on the number of items to run (in my case it is more than 100 tasks!). But it also looks that increasing delay time will have adverse effect on cancel buttons as they are not working with high values of delay setting.  
Is this issue only for working with features and not with the images?

**Comment by jkittner** [comment]
That's indeed a lot of tasks.
I did not change anything for cancelling and the delay has no effect here.
It seems like there's some more work to do. Those other issues might also be due to the ee UI being at its limits -- hitting ~100 buttons almost at the same time is not the easiest task.
Maybe you should have a look at the Python API for earthengine for your project instead?

**Comment by shahriar49** [comment]
You are right. It looks like I should switch to python API and not to try it this way. The GEE code editor window behavior is not consistent when I change the number of tasks and delay values, and although each task is a small one, running a lot of them concurrently will make GEE crazy.

**Comment by jkittner** [comment]
Hi, I found another small bug in yesterdays code. The promise was not working as expected. I fixed this now and tested it against up to 30 tasks for images and features `toDrive`. While being slow for `toAsset` exports it seems to work reliably now. I also added some more information to the readme explaining the the behavior and also limitation and challenges -- have a look if you want.
